import pandas as pd
data = pd.read_csv("iris.csv")

meanpetalength = data["petal_length"].mean()
print(meanpetalength)
meanpwidth = data["petal_width"].mean()
print(meanpwidth)
meanseplen = data["sepal_length"].mean()
print(meanseplen)
meansepwidth = data["sepal_width"].mean()
print(meansepwidth)
print("-" * 50)
minpetalength = data["petal_length"].min()
print(minpetalength)
minpwidth = data["petal_width"].min()
print(minpwidth)
minseplen = data["sepal_length"].min()
print(minseplen)
minsepwidth = data["sepal_width"].min()
print(minsepwidth)
print("-" * 50)
maxpetalength = data["petal_length"].max()
print(maxpetalength)
maxpwidth = data["petal_width"].max()
print(maxpwidth)
maxseplen = data["sepal_length"].max()
print(maxseplen)
maxsepwidth = data["sepal_width"].max()
print(maxsepwidth)